### PR TITLE
UI/UX Improvements

### LINKED ISSUE #1: [Feature] : UI/UX Improvements
Improve the UI by adding background theme, styling navbar and creating home page

### PR DESCRIPTION
**Pull request by Vansh-Parate**
Resolves #1

Before :
[Screencast from 2024-10-04 01-19-47.webm](https://github.com/user-attachments/assets/04124b9f-eb52-487a-b245-c84126b9a4e1)

After : 
[Screencast from 2024-10-04 01-14-16.webm](https://github.com/user-attachments/assets/f84683e6-b001-4b57-a294-4cb360507dae)

Changes : 
🌟 Added new background theme.
🌟 Styled the navbar.
🌟 Crafted the **Home** Page.
🌟 Made the website **Reponsive**

### CODE REVIEW

**Comment by Vansh-Parate** [comment]
@techcsispit please review and merge it.

**Comment by techcsispit** [comment]
@Vansh-Parate Don't add the node modules

**Comment by Vansh-Parate** [comment]
How to remove them? I have used some library icons

**Comment by techcsispit** [comment]
Add a `.gitignore` file and write `node_modules/` inside that

**Comment by Vansh-Parate** [comment]
Done please check now.

**Comment by techcsispit** [comment]
Well done

**Pull request merged**
